Updated github workflows

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,11 +1,11 @@
-name: PHPUnit and Acceptance Tests
+name: Tests
 on: [push]
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 jobs:
   phpunit:
-    name: PHPUnit Coverage Tests
+    name: PHPUnit
     runs-on: ubuntu-latest
     container:
       image: pookmish/drupal8ci:php8.3
@@ -30,17 +30,18 @@ jobs:
             docroot/core
             docroot/libraries
             docroot/modules/contrib
-          key: caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+          key: 6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
           restore-keys: |
-            caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            caw-${{ hashFiles('composer.json') }}-
-            caw-
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-
+            6.x-${{ vars.CACHE_KEY }}-
       - name: Run Unit Tests
         env:
           CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
         run: |
           git config --system --add safe.directory '*' &&
           composer install -n &&
+          mkdir -p docroot/sites/simpletest &&
           drush sws:source:tests:phpunit --db-host=mysql --db-pass=drupal --db-name=drupal --db-user=drupal --with-coverage &&
           drush sws:tests:phpunit-coverage-check artifacts/phpunit/coverage/xml --clover-file=artifacts/phpunit/coverage/clover.xml -n
       - name: Save Test Results
@@ -50,6 +51,7 @@ jobs:
           name: unit-tests-results
           path: $GITHUB_WORKSPACE/artifacts
   sites_to_test:
+    name: Sites to test
     runs-on: ubuntu-latest
     container:
       image: pookmish/drupal8ci:php8.3
@@ -65,25 +67,40 @@ jobs:
             docroot/core
             docroot/libraries
             docroot/modules/contrib
-          key: caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+          key: 6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
           restore-keys: |
-            caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            caw-${{ hashFiles('composer.json') }}-
-            caw-
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-
+            6.x-${{ vars.CACHE_KEY }}-
       - name: Get Sites
         id: set-matrix
         run: |
           composer install -n &&
           SITES=$(echo -n "$(drush sws:drush-config command.sws.options.multisites | grep -v default)" | jq -R -s -c 'split("\n") | sort') &&
           echo "matrix=$SITES" >> $GITHUB_OUTPUT
+  shard_matrix:
+    name: Test Shards
+    runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Generate Shard Matrix
+        id: set-matrix
+        run: |
+          n=${{ vars.TEST_SHARDS || 3 }} &&
+          numbers=($(seq 1 $n)) &&
+          json=$(printf '%s\n' "${numbers[@]}" | jq -R . | jq -s -c .) &&
+          echo "Test shards: $json" &&
+          echo "matrix=$json" >> $GITHUB_OUTPUT
   codeception:
-    name: Codeception Test Suites
-    needs: sites_to_test
+    name: Codeception
+    needs: [sites_to_test, shard_matrix]
     strategy:
       fail-fast: false
       matrix:
-        suite: [acceptance, functional]
         site: ${{fromJSON(needs.sites_to_test.outputs.matrix)}}
+        suite: [acceptance, functional]
+        shard: ${{fromJSON(needs.shard_matrix.outputs.matrix)}}
     runs-on: ubuntu-latest
     container:
       image: pookmish/drupal8ci:php8.3
@@ -114,11 +131,11 @@ jobs:
             docroot/core
             docroot/libraries
             docroot/modules/contrib
-          key: caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+          key: 6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
           restore-keys: |
-            caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            caw-${{ hashFiles('composer.json') }}-
-            caw-
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-
+            6.x-${{ vars.CACHE_KEY }}-
       - name: Install Site
         run: |
           git config --system --add safe.directory '*' &&
@@ -138,9 +155,9 @@ jobs:
           mkdir -p artifacts/_data/
       - name: Run tests
         run: |
-          mkdir -p -m 777 tests/codeception/${{ matrix.suite }} &&
+          n=${{ vars.TEST_SHARDS || 3 }} &&
           PROFILE=`drush st --fields=install-profile --format=list` &&
-          drush codeception --site-domain=localhost --suite=${{ matrix.suite }} &&
+          drush codeception --site-domain=localhost --suite=${{ matrix.suite }} --test-dir=docroot/profiles/custom/$PROFILE/tests/codeception --shard=${{ matrix.shard }}/$n &&
           if [ ! -f artifacts/report.html ]; then
             exit 1
           fi
@@ -148,10 +165,10 @@ jobs:
         uses: actions/upload-artifact@v4
         if: always()
         with:
-          name: ${{ matrix.site }}-${{ matrix.suite }}-tests-results
+          name: ${{ matrix.site }}-${{ matrix.suite }}-${{ matrix.shard }}-tests-results
           path: artifacts
   db_updates:
-    name: Verify Database Updates & Config Imports
+    name: DB Updates
     needs: sites_to_test
     strategy:
       fail-fast: false
@@ -180,7 +197,7 @@ jobs:
         with:
           key: ${{ secrets.SSH_KEY }}
           name: id_rsa
-          known_hosts: ${{ secrets.CAW_KNOWN_HOSTS }}
+          known_hosts: ${{ secrets.KNOWN_HOSTS }}
           if_key_exists: fail
       - uses: actions/checkout@v4
       - name: Restore Cache
@@ -191,11 +208,11 @@ jobs:
             docroot/core
             docroot/libraries
             docroot/modules/contrib
-          key: caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+          key: 6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
           restore-keys: |
-            caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            caw-${{ hashFiles('composer.json') }}-
-            caw-
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-
+            6.x-${{ vars.CACHE_KEY }}-
       - name: Sync and Update Site
         run: |
           git config --system --add safe.directory '*' &&
@@ -208,8 +225,24 @@ jobs:
           apachectl stop &&
           apachectl start &&
           composer install -n &&
+          drush sa @${{ matrix.site }}.prod || exit 0 &&
           drush drupal:sync --site=${{ matrix.site }} -n &&
           curl -I http://localhost --fail
+  all-tests-pass:
+    name: All Tests Pass
+    needs: [phpunit, codeception, db_updates]
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo 'Passed'
+  something_failed:
+    name: Something Failed
+    if: failure()
+    needs: [phpunit, codeception, db_updates]
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          echo "something failed"
+          exit 1
   deploy:
     name: Deploy Artifact
     needs: [phpunit, codeception, db_updates]
@@ -226,17 +259,17 @@ jobs:
             docroot/core
             docroot/libraries
             docroot/modules/contrib
-          key: caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+          key: 6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
           restore-keys: |
-            caw-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
-            caw-${{ hashFiles('composer.json') }}-
-            caw-
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-${{ hashFiles('composer.lock') }}
+            6.x-${{ vars.CACHE_KEY }}-${{ hashFiles('composer.json') }}-
+            6.x-${{ vars.CACHE_KEY }}-
       - name: Install SSH key
         uses: shimataro/ssh-key-action@v2
         with:
           key: ${{ secrets.SSH_KEY }}
           name: id_rsa
-          known_hosts: ${{ secrets.CAW_KNOWN_HOSTS }}
+          known_hosts: ${{ secrets.KNOWN_HOSTS }}
           if_key_exists: fail
       - name: Deploy Artifact
         run: |
